// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"review-job/internal/conf"
	"review-job/internal/job"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(server *conf.Server, data *conf.Data, kafka *conf.Kafka, es *conf.ES, logger log.Logger) (*kratos.App, func(), error) {
	reader := job.NewKafkaReader(kafka)
	esCli := job.NewESCli(es)
	jobServer := job.NewJobServer(reader, esCli, logger)
	app := newApp(logger, jobServer)
	return app, func() {
	}, nil
}
